version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: EST
  open-pull-requests-limit: 10
  reviewers:
  - karelhala
  allow:
  - dependency-name: "@redhat-cloud-services/frontend*"
  - dependency-name: "@patternfly/*"
    dependency-type: direct
  ignore:
  - dependency-name: "@redhat-cloud-services/frontend-components-remediations"
    versions:
    - 2.3.10
    - 3.0.0
    - 3.1.13
    - 3.1.14
  - dependency-name: "@redhat-cloud-services/frontend-components-config"
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.10
    - 4.0.11
    - 4.0.13
    - 4.0.14
    - 4.0.16
    - 4.0.17
    - 4.0.18
    - 4.0.19
    - 4.0.2
    - 4.0.20
    - 4.0.21
    - 4.0.22
    - 4.0.23
    - 4.0.25
    - 4.0.26
    - 4.0.27
    - 4.0.3
    - 4.0.4
    - 4.0.5
    - 4.0.6
    - 4.0.7
    - 4.0.8
    - 4.0.9
  - dependency-name: "@redhat-cloud-services/frontend-components"
    versions:
    - 3.0.1
    - 3.0.10
    - 3.0.11
    - 3.0.2
    - 3.0.3
    - 3.0.5
    - 3.0.6
    - 3.0.7
    - 3.0.8
    - 3.0.9
    - 3.1.0
    - 3.1.1
    - 3.1.10
    - 3.1.2
    - 3.1.3
    - 3.1.4
    - 3.1.5
    - 3.1.6
    - 3.1.7
    - 3.1.8
    - 3.1.9
  - dependency-name: "@redhat-cloud-services/frontend-components-inventory-patchman"
    versions:
    - 1.10.0
    - 1.11.0
    - 1.11.2
    - 1.11.3
    - 1.12.1
    - 1.13.0
    - 1.14.0
    - 1.14.1
    - 1.14.2
    - 1.14.3
    - 1.15.0
    - 1.16.0
    - 1.16.1
    - 1.16.2
    - 1.17.0
    - 1.17.10
    - 1.17.11
    - 1.17.2
    - 1.17.3
    - 1.17.4
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.8.3
    - 1.8.4
    - 1.9.0
    - 1.9.1
  - dependency-name: "@patternfly/react-icons"
    versions:
    - 4.10.1
    - 4.8.4
    - 4.9.0
    - 4.9.1
    - 4.9.2
    - 4.9.9
  - dependency-name: "@patternfly/react-core"
    versions:
    - 4.106.1
    - 4.106.2
    - 4.115.1
    - 4.90.2
    - 4.97.2
  - dependency-name: "@redhat-cloud-services/frontend-components-utilities"
    versions:
    - 3.0.3
    - 3.1.0
    - 3.1.1
  - dependency-name: "@redhat-cloud-services/frontend-components-inventory-insights"
    versions:
    - 3.0.1
    - 3.0.2
    - 3.1.1
    - 3.1.2
    - 3.1.3
  - dependency-name: "@redhat-cloud-services/frontend-components-inventory-general-info"
    versions:
    - 3.0.0
    - 3.1.3
  - dependency-name: "@redhat-cloud-services/frontend-components-pdf-generator"
    versions:
    - 2.3.10
    - 2.3.9
    - 2.4.0
    - 2.5.2
  - dependency-name: "@redhat-cloud-services/frontend-components-translations"
    versions:
    - 3.1.1
  - dependency-name: "@redhat-cloud-services/frontend-components-notifications"
    versions:
    - 3.0.2
    - 3.0.3
  - dependency-name: "@patternfly/react-table"
    versions:
    - 4.20.15
    - 4.23.2
