version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps):"
    groups:
      fec:
        patterns:
          - "@redhat-cloud-services/*"
        exclude-patterns:
          - "@redhat-cloud-services/*-client"
      patternfly:
        patterns:
          - "@patternfly/*"
        exclude-patterns:
          - "@patternfly/react-charts"
        update-types:
          - "minor"
          - "patch"
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      lint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "stylelint*"
      clients:
        patterns:
          - "@redhat-cloud-services/*-client"
      jest:
        patterns:
          - "jest*"
      cypress:
        patterns:
          - "*cypress*"
      react:
        patterns:
          - "react"
          - "react-dom"
      webpack:
        patterns:
          - "webpack"
          - "webpack-bundle-analyzer"