import type { ViewOut } from '../../../../api/inventoryViewsApi';

export const ALL_SYSTEMS_MOCK_ID = '506da034-39ab-41be-a6f4-1d7f1b8d0b73';

export const MOCK_VIEWS: ViewOut[] = [
  {
    id: ALL_SYSTEMS_MOCK_ID,
    name: 'All systems',
    description: 'Default inventory view showing all systems.',
    is_system_view: true,
    org_id: null,
    org_wide: true,
    configuration: {
      columns: [
        { key: 'display_name' },
        { key: 'group_name' },
        { key: 'operating_system' },
        { key: 'last_check_in' },
      ],
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    is_owner: false,
  },
  {
    id: 'view-production',
    name: 'Production view',
    description: 'Production environment systems',
    is_system_view: false,
    org_id: 'org-123',
    org_wide: false,
    configuration: {
      columns: [
        { key: 'display_name' },
        { key: 'group_name' },
        { key: 'operating_system' },
        { key: 'last_check_in' },
        { key: 'advisor:recommendations' },
        { key: 'vulnerability:total_cves' },
      ],
      sort: { key: 'display_name', direction: 'asc' },
      filters: {},
    },
    created_by: 'current-user',
    created_at: '2026-06-15T10:00:00Z',
    updated_at: '2026-07-20T14:30:00Z',
    is_owner: true,
  },
  {
    id: 'view-rhel9-staging',
    name: 'RHEL 9 staging',
    description: 'RHEL 9 systems in staging environment',
    is_system_view: false,
    org_id: 'org-123',
    org_wide: false,
    configuration: {
      columns: [
        { key: 'display_name' },
        { key: 'operating_system' },
        { key: 'last_check_in' },
        { key: 'patch:advisories_rhsa_installable' },
        { key: 'advisor:recommendations' },
      ],
      sort: { key: 'patch:advisories_rhsa_installable', direction: 'desc' },
      filters: {},
    },
    created_by: 'current-user',
    created_at: '2026-07-01T09:00:00Z',
    updated_at: '2026-07-25T11:00:00Z',
    is_owner: true,
  },
  {
    id: 'view-security',
    name: 'Security overview',
    description: 'Systems with security-related advisories',
    is_system_view: true,
    org_id: 'org-123',
    org_wide: true,
    configuration: {
      columns: [
        { key: 'display_name' },
        { key: 'operating_system' },
        { key: 'last_check_in' },
        { key: 'vulnerability:total_cves' },
        { key: 'vulnerability:critical_cves' },
        { key: 'vulnerability:important_cves' },
        { key: 'vulnerability:cves_with_known_exploits' },
        { key: 'advisor:recommendations' },
        { key: 'advisor:incidents' },
        { key: 'compliance:last_scan' },
      ],
      sort: { key: 'vulnerability:critical_cves', direction: 'desc' },
    },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    is_owner: false,
  },
];
