import type { ViewOut } from '../../../../api/inventoryViewsApi';
import { ALL_SYSTEMS_VIEW_ID } from '../../../../api/inventoryViewsApi';

export const MOCK_VIEWS: ViewOut[] = [
  {
    id: ALL_SYSTEMS_VIEW_ID,
    name: 'All systems',
    description: 'Default view showing all inventory systems',
    is_system_view: true,
    org_id: 'org-123',
    org_wide: true,
    configuration: { columns: [] },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    is_owner: false,
  },
  {
    id: 'view-production',
    name: 'Production view',
    description: 'Production environment systems',
    is_system_view: false,
    org_id: 'org-123',
    org_wide: false,
    configuration: { columns: [] },
    created_by: 'current-user',
    created_at: '2026-06-15T10:00:00Z',
    updated_at: '2026-07-20T14:30:00Z',
    is_owner: true,
  },
  {
    id: 'view-rhel9-staging',
    name: 'RHEL 9 staging',
    description: 'RHEL 9 systems in staging environment',
    is_system_view: false,
    org_id: 'org-123',
    org_wide: false,
    configuration: { columns: [] },
    created_by: 'current-user',
    created_at: '2026-07-01T09:00:00Z',
    updated_at: '2026-07-25T11:00:00Z',
    is_owner: true,
  },
  {
    id: 'view-security',
    name: 'Security overview',
    description: 'Systems with security-related advisories',
    is_system_view: true,
    org_id: 'org-123',
    org_wide: true,
    configuration: { columns: [] },
    created_by: 'system',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    is_owner: false,
  },
];
