name: Auto-Approve Konflux PRs

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'red-hat-konflux[bot]'

    permissions:
      pull-requests: write

    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "This PR from Konflux has been automatically approved."
