name: Auto-Approve Dependency-Update PRs

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'red-hat-konflux[bot]' || github.event.pull_request.user.login == 'dependabot[bot]' }}

    permissions:
      pull-requests: write

    steps:
      - name: Metadata for PR
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        id: metadata
        uses: dependabot/fetch-metadata@dbb049abf0d677abbd7f7eee0375145b417fdd34 # v2.2.0
        # NOTE:
        # the @V2 in the previous line "uses: dependabot/fetch-metadata@v2" made it mutable and a security risk.
        # To make it mutable, use a specific SHA, like dbb049abf0d677abbd7f7eee0375145b417fdd34. 
        # which was provided by running 
        # "gh api repos/dependabot/fetch-metadata/git/ref/tags/v2.2.0 --jq '.object.sha'"
        # To update it automatically, add the following to the dependabot.yml file:
        #   - package-ecosystem: "github-actions"
        #     directory: "/"
        #     schedule:
        #       interval: "weekly"
        #     labels:
        #       - "dependencies"
        #     commit-message:
        #       prefix: "ci(deps):"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto-approve PR
        if: ${{ github.event.pull_request.user.login == 'red-hat-konflux[bot]' ||
                (github.event.pull_request.user.login == 'dependabot[bot]' &&
                contains(github.event.pull_request.labels.*.name, 'dependencies') && (
                  steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
                  steps.metadata.outputs.update-type == 'version-update:semver-patch'
                ))}}
        uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "This dependency-update PR has been automatically approved."
